AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an IAM role for a Lambda function and attach a JSON policy document from an S3 bucket.

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket containing the policy document.
    Default: 'YOUR_BUCKET_NAME'
  KeyName:
    Type: String
    Description: The name of the S3 bucket containing the policy document.
    Default: 'KEY_NAME'
  LambdaExecutionPolicyName:
    Type: String
    Description: The name of the policy to attach to the Lambda execution role.
    Default: 'LambdaExecutionPolicy'
  LambdaExecutionRoleName:
    Type: String
    Description: The name of the role to create for the Lambda function.
    Default: 'LambdaExecutionRole'
  ServiceName:
    Type: String
    Description: The name of the service that the Lambda function will interact with.
    Default: 'lambda.amazonaws.com'

Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - !Ref ServiceName
            Action: 
              - 'sts:AssumeRole'
  LambdaExecutionPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Ref LambdaExecutionPolicyName
      Roles:
        - !Ref LambdaExecutionRole
      PolicyDocument: 
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub 's3://${BucketName}/${KeyName}'

Outputs:
  AccountId:
    Description: AWS Account ID
    Value: !Ref AWS::AccountId
  RegionName:
    Description: AWS Region Name
    Value: !Ref AWS::Region
  StackId:
    Description: Current Stack ID
    Value: !Ref AWS::StackId
  StackName:
    Description: Current Stack Name
    Value: !Ref AWS::StackName
  RoleName:
    Description: The name of the IAM role that was created.
    Value: !Ref LambdaExecutionRole
    Export:
      Name: LambdaExecutionRoleName
  RoleArn:
    Description: The ARN of the IAM role that was created.
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRoleArn
  PolicyName:
    Description: The name of the policy that was attached to the IAM role.
    Value: !Ref LambdaExecutionPolicy
    Export:
      Name: LambdaExecutionPolicyName